export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "qa",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "api",
        "application",
        "build",
        "ci",
        "config",
        "data",
        "docs",
        "domain",
        "e2e",
        "infra",
        "integration",
        "interfaces",
        "models",
        "operations",
        "release",
        "repo",
        "scripts",
        "security",
        "support",
        "tests",
        "tools",
        "unit",
        "user",
        "wallet",
      ],
    ],
    "scope-empty": [0],
    "subject-empty": [2, "never"],
    "type-empty": [2, "never"],
    "header-max-length": [2, "always", 100],
    "body-max-line-length": [2, "always", 100],
    "subject-case": [0],
  },
};
