### Go Wallet Core API - API Playground

@host = http://localhost:8080

### [GET] Health Check
GET {{host}}/health
Accept: application/json

---

### [POST] Criar Usuário (User)
POST {{host}}/users
Content-Type: application/json

{
    "id": "USER-001",
    "name": "Victor Silveira",
    "email": "victor@teste.com"
}

---

### [POST] Depositar Crédito (Deposit) na Conta Default
POST {{host}}/wallet/transaction
Content-Type: application/json

{
    "account_id": "ACC-001",
    "type": "CREDIT",
    "amount": 25050,
    "description": "Depósito Mensal via PIX (R$ 250,50)"
}

---

### [POST] Sacar Débito (Withdraw)
POST {{host}}/wallet/transaction
Content-Type: application/json

{
    "account_id": "ACC-001",
    "type": "DEBIT",
    "amount": 10000,
    "description": "Pagamento de Academia (R$ 100,00)"
}

---

### [POST] Tentar Saque Sem Saldo (Error Case)
POST {{host}}/wallet/transaction
Content-Type: application/json

{
    "account_id": "ACC-001",
    "type": "DEBIT",
    "amount": 100000000,
    "description": "Tentativa Frustrada (valor acima do saldo)"
}
